"""Rename table 'student_requests' to 'male_student_requests' and delete column 'gender' in it

Revision ID: 1fd2cb0a2c0a
Revises: 5b1cc49b3e5e
Create Date: 2024-12-09 19:30:54.177216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd2cb0a2c0a'
down_revision = '5b1cc49b3e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('male_student_requests',
    sa.Column('student_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bedtime_habit', sa.String(), nullable=False),
    sa.Column('social_style', sa.String(), nullable=False),
    sa.Column('religion', sa.String(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('sports_passion', sa.Integer(), nullable=False),
    sa.Column('music_passion', sa.Integer(), nullable=False),
    sa.Column('gaming_passion', sa.Integer(), nullable=False),
    sa.Column('average_monthly_spending', sa.Integer(), nullable=False),
    sa.Column('is_smoker', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.drop_table('student_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_requests',
    sa.Column('student_id', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('bedtime_habit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('social_style', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('religion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('academic_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sports_passion_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('music_passion_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gaming_passion_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_monthly_spending', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_smoker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('student_id', name='student_requests_pkey')
    )
    op.drop_table('male_student_requests')
    # ### end Alembic commands ###
