"""Initial migration

Revision ID: 2b078f16990f
Revises: 
Create Date: 2024-11-28 00:56:35.488124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b078f16990f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_name', sa.String(length=5), nullable=False),
    sa.Column('total_floors', sa.Integer(), nullable=False),
    sa.Column('rooms_per_floor', sa.Integer(), nullable=False),
    sa.Column('rent_per_month', sa.Integer(), nullable=False),
    sa.Column('people_per_room', sa.Integer(), nullable=False),
    sa.Column('private_toilet', sa.Integer(), nullable=False),
    sa.Column('water_heater', sa.Integer(), nullable=False),
    sa.Column('air_conditioner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_name')
    )
    op.create_table('student_requests',
    sa.Column('student_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=6), nullable=False),
    sa.Column('rent_per_month', sa.Integer(), nullable=False),
    sa.Column('people_per_room', sa.Integer(), nullable=False),
    sa.Column('private_toilet', sa.Integer(), nullable=False),
    sa.Column('water_heater', sa.Integer(), nullable=False),
    sa.Column('air_conditioner', sa.Integer(), nullable=False),
    sa.Column('primary_study_time', sa.String(), nullable=False),
    sa.Column('social_style', sa.String(), nullable=False),
    sa.Column('silent_space_required', sa.Boolean(), nullable=False),
    sa.Column('bed_time_habit', sa.String(), nullable=False),
    sa.Column('is_smoker', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(length=8), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('building_name', sa.String(length=5), nullable=False),
    sa.Column('dormitory_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['dormitory_id'], ['dormitories.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_requests.student_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('student_requests')
    op.drop_table('dormitories')
    # ### end Alembic commands ###
