"""Initial Migration

Revision ID: 442a00d81f7c
Revises: 
Create Date: 2024-12-05 21:53:53.590352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442a00d81f7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_requests',
    sa.Column('student_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=5), nullable=False),
    sa.Column('bed_time_habit', sa.String(), nullable=False),
    sa.Column('social_style', sa.String(), nullable=False),
    sa.Column('religion', sa.String(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('sports_passion', sa.String(), nullable=False),
    sa.Column('music_passion', sa.String(), nullable=False),
    sa.Column('gaming_passion', sa.String(), nullable=False),
    sa.Column('average_monthly_spending', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_requests')
    # ### end Alembic commands ###
