"""Delete table 'dormitories', add new table 'rooms'

Revision ID: 5b1cc49b3e5e
Revises: 25d6a666b398
Create Date: 2024-12-07 18:00:14.491958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1cc49b3e5e'
down_revision = '25d6a666b398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    op.drop_table('dormitories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitories',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('building_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_rooms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('students_per_room', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dormitories_pkey')
    )
    op.drop_table('rooms')
    # ### end Alembic commands ###
