"""Initial Migration

Revision ID: d93ae92ce735
Revises: 
Create Date: 2024-12-07 02:09:45.774583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93ae92ce735'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('building_name', sa.String(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('students_per_room', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('k_means_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_requests',
    sa.Column('student_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(length=5), nullable=False),
    sa.Column('bedtime_habit', sa.String(), nullable=False),
    sa.Column('social_style', sa.String(), nullable=False),
    sa.Column('religion', sa.String(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('sports_passion_score', sa.Integer(), nullable=False),
    sa.Column('music_passion_score', sa.Integer(), nullable=False),
    sa.Column('gaming_passion_score', sa.Integer(), nullable=False),
    sa.Column('average_monthly_spending', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_requests')
    op.drop_table('k_means_results')
    op.drop_table('dormitories')
    # ### end Alembic commands ###
