"""empty message

Revision ID: e64011059dfb
Revises: fec8c7c814ba
Create Date: 2024-12-13 21:04:28.207863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64011059dfb'
down_revision = 'fec8c7c814ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeled_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labeled_data')
    # ### end Alembic commands ###
